### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by bumer0** [jordenc/com.lg.smarttv#3]
could you update?

**Comment by jordenc** [comment]
Try to use the "official"  app by Athom at https://apps.athom.com/app/com.lg.webos

This one will not get any updates.

**Comment by bumer0** [comment]
![2018-03-05 16-32-49 miniserver local - chrome](https://user-images.githubusercontent.com/31984665/36977624-dea1d864-2092-11e8-8283-ad2c84c4d8d3.jpg)

**Comment by jsm198** [comment]
Why is the issue closed when not resolved?

**Comment by jordenc** [comment]
Because this app is abandoned, I will not update it. And Athom released their own app which works for me and is still updated.
